Improvement/reorganize folder
Nerolation/makerdao_uniswap_integration pull request #4
Opened 2021-03-26 09:59 UTC by edd34

The idea is to improve the folder structure of the project in order to make it more maintainable and upgradable.

I have done the following tasks :
1) Split EthLeverager.sol contract to :
* contract/CallerContract.sol
* contract/EthLeverager.sol
* contract/HelperContract.sol
* contract/Interfaces.sol

2) move contracts/abi.txt and contracts/bytecode.txt to respectively build/abi.txt and build/bytecode.txt

3) Format the smartcontracts

4) Update EthLeverageWallet.py to find abi and bytecode in build folder

5) change pragma solidity to allow the program to be compiled by solc v0.8.x using '^'

[x] You can still compile the project using `solc contract/EthLeverager.sol`
[x] I have tested the project using test.py and my own blockchain provider url, and it works well

2021-03-26 10:34 UTC, edd34 commented on test.py
> +i_EthLW = EthLeverage().init(http_rpc)
I used the name EthLeverage  because it's more meaningful than MyContract. i_EthLW stands for "instance of EthLeverageWallet"

2021-03-26 10:47 UTC, edd34 commented
I have also updated the notebook with recent changes on folder structure

2021-03-26 11:11 UTC, Nerolation requested changes
there is a type in the description (move EthLevergaWallet... instead of move EthLeverageWallet)

2021-03-26 11:48 UTC, edd34 commented
> there is a type in the description (move EthLevergaWallet... instead of move EthLeverageWallet)

Resolved

2021-03-27 08:53 UTC, Nerolation commented
approved

2021-03-27 08:53 UTC, merged